### ISSUE TITLE
Change teams

### ISSUE THREAD

**Issue by Luselmases** [ABJ4403/Payback2_CHEATus#12]
### Checklist

- [ ] I am using the latest version of the script
- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Hi,in the first thanks for share the scripts congratulations al is so good i played all the summer and 2023,i only play in offline because is so funny for me,thanks to the script i can control the ai bots that all in my life i wanted,but this is not an isue is recommendation.Can you put a script to change teams on offline?becuase i want to have bases that the team B only have,i wait the answer and thanks.

### Steps to reproduce

1. 
2. 
3.

**Comment by ABJ4403** [comment]
I think what you meant is you want to change your team to opponent team (in CTS, Gang warfare, and conquest matches) latest version of the script already has this new cheat (since 2.4.9 IIRC), to activate it, use floodspawn menu, and activate from there, you will see bunch of menus, and one of them is "Swap Teams", maybe its at 0 or 1, you can slide that to other direction to change team

I'll close the issue, if there is any problem i may repoen this again
you can download the latest version of Payback2_CHEATus to have all the latest features and stuff

**Comment by ABJ4403** [comment]
I think what you meant is you want to change your team to opponent team (in CTS, Gang warfare, and conquest matches) latest version of the script already has this new cheat (since 2.4.9 IIRC), to activate it, use floodspawn menu, and activate from there, you will see bunch of menus, and one of them is "Swap Teams", maybe its at 0 or 1, you can slide that to other direction to change team

I'll close the issue, if there is any problem i may repoen this again
you can download the latest version of Payback2_CHEATus to have all the latest features and stuff

**Comment by Luselmases** [comment]
Thank you for answer the question im going to try now i after i answer how it was thanks.

**Comment by Luselmases** [comment]
When i go to use the script in the versión 2.104.12.4 says that script was finished

**Comment by Luselmases** [comment]
How i download the version 2.106.0 for the script to gg detect?

**Comment by Luselmases** [comment]
Sorry,i get achieve change my team,but i dont know how to appear in the base at the start of the game

**Comment by Luselmases** [comment]
Okay i change the team it was crazy thanks for all but only that i appear in the other base team how i can change the chekpoint?
